@startuml

|リーダー|
start
:**熱湯風呂入ったらおいしいよね。おれやるよ。**;


|ジモンさん|
:**いやいや、俺がやるよ。**;

|リーダー|
:**おれやるよ。**;

|竜さん|
:**じゃあ、俺がやるよ。**;

|リーダー|
fork
:**どうぞ、どうぞ**;

|ジモンさん|
fork again
:**どうぞ、どうぞ**;

|竜さん|
end fork
:**おい!!!**;

|リーダー|
fork
:**やー!!!**;

|ジモンさん|
forkagain
:**やー!!!**;

|竜さん|
forkagain
:**やー!!!**;
end fork

stop
@enduml
